tasks = [
	{'id'= 1, 'name'= 'Task 1', 'period'= 500, 'execution_time'= 100, 'deadline'= 392, 'priority'= 42},
	{'id'= 2, 'name'= 'Task 2', 'period'= 700, 'execution_time'= 91, 'deadline'= 401, 'priority'= 39},
	{'id'= 3, 'name'= 'Task 3', 'period'= 800, 'execution_time'= 55, 'deadline'= 434, 'priority'= 97},
	{'id'= 4, 'name'= 'Task 4', 'period'= 100, 'execution_time'= 94, 'deadline'= 395, 'priority'= 5},
	{'id'= 5, 'name'= 'Task 5', 'period'= 600, 'execution_time'= 47, 'deadline'= 597, 'priority'= 6},
	{'id'= 6, 'name'= 'Task 6', 'period'= 900, 'execution_time'= 53, 'deadline'= 67, 'priority'= 81},
	{'id'= 7, 'name'= 'Task 7', 'period'= 300, 'execution_time'= 44, 'deadline'= 885, 'priority'= 8},
	{'id'= 8, 'name'= 'Task 8', 'period'= 700, 'execution_time'= 93, 'deadline'= 498, 'priority'= 85},
	{'id'= 9, 'name'= 'Task 9', 'period'= 700, 'execution_time'= 78, 'deadline'= 648, 'priority'= 75},
	{'id'= 10, 'name'= 'Task 10', 'period'= 100, 'execution_time'= 94, 'deadline'= 349, 'priority'= 6},
	{'id'= 11, 'name'= 'Task 11', 'period'= 300, 'execution_time'= 62, 'deadline'= 981, 'priority'= 45},
	{'id'= 12, 'name'= 'Task 12', 'period'= 600, 'execution_time'= 85, 'deadline'= 970, 'priority'= 29},
	{'id'= 13, 'name'= 'Task 13', 'period'= 800, 'execution_time'= 40, 'deadline'= 824, 'priority'= 22},
	{'id'= 14, 'name'= 'Task 14', 'period'= 400, 'execution_time'= 33, 'deadline'= 788, 'priority'= 95},
	{'id'= 15, 'name'= 'Task 15', 'period'= 800, 'execution_time'= 70, 'deadline'= 689, 'priority'= 47},
	{'id'= 16, 'name'= 'Task 16', 'period'= 700, 'execution_time'= 10, 'deadline'= 809, 'priority'= 6},
	{'id'= 17, 'name'= 'Task 17', 'period'= 300, 'execution_time'= 63, 'deadline'= 618, 'priority'= 64},
	{'id'= 18, 'name'= 'Task 18', 'period'= 200, 'execution_time'= 70, 'deadline'= 882, 'priority'= 73},
	{'id'= 19, 'name'= 'Task 19', 'period'= 100, 'execution_time'= 97, 'deadline'= 638, 'priority'= 4},
	{'id'= 20, 'name'= 'Task 20', 'period'= 300, 'execution_time'= 94, 'deadline'= 64, 'priority'= 95},
	{'id'= 21, 'name'= 'Task 21', 'period'= 600, 'execution_time'= 26, 'deadline'= 957, 'priority'= 80},
	{'id'= 22, 'name'= 'Task 22', 'period'= 900, 'execution_time'= 97, 'deadline'= 140, 'priority'= 80},
	{'id'= 23, 'name'= 'Task 23', 'period'= 600, 'execution_time'= 57, 'deadline'= 598, 'priority'= 26},
	{'id'= 24, 'name'= 'Task 24', 'period'= 200, 'execution_time'= 26, 'deadline'= 962, 'priority'= 49},
	{'id'= 25, 'name'= 'Task 25', 'period'= 600, 'execution_time'= 41, 'deadline'= 572, 'priority'= 81},
	{'id'= 26, 'name'= 'Task 26', 'period'= 400, 'execution_time'= 63, 'deadline'= 389, 'priority'= 5},
	{'id'= 27, 'name'= 'Task 27', 'period'= 500, 'execution_time'= 79, 'deadline'= 769, 'priority'= 29},
	{'id'= 28, 'name'= 'Task 28', 'period'= 200, 'execution_time'= 77, 'deadline'= 894, 'priority'= 51},
	{'id'= 29, 'name'= 'Task 29', 'period'= 1000, 'execution_time'= 61, 'deadline'= 214, 'priority'= 40},
	{'id'= 30, 'name'= 'Task 30', 'period'= 400, 'execution_time'= 17, 'deadline'= 560, 'priority'= 57},
	{'id'= 31, 'name'= 'Task 31', 'period'= 1000, 'execution_time'= 64, 'deadline'= 640, 'priority'= 33},
	{'id'= 32, 'name'= 'Task 32', 'period'= 700, 'execution_time'= 69, 'deadline'= 674, 'priority'= 97},
	{'id'= 33, 'name'= 'Task 33', 'period'= 800, 'execution_time'= 34, 'deadline'= 197, 'priority'= 44},
	{'id'= 34, 'name'= 'Task 34', 'period'= 800, 'execution_time'= 97, 'deadline'= 358, 'priority'= 5},
	{'id'= 35, 'name'= 'Task 35', 'period'= 300, 'execution_time'= 91, 'deadline'= 640, 'priority'= 68},
	{'id'= 36, 'name'= 'Task 36', 'period'= 1000, 'execution_time'= 95, 'deadline'= 324, 'priority'= 19},
	{'id'= 37, 'name'= 'Task 37', 'period'= 900, 'execution_time'= 80, 'deadline'= 753, 'priority'= 93},
	{'id'= 38, 'name'= 'Task 38', 'period'= 500, 'execution_time'= 41, 'deadline'= 695, 'priority'= 69},
	{'id'= 39, 'name'= 'Task 39', 'period'= 500, 'execution_time'= 18, 'deadline'= 303, 'priority'= 94},
	{'id'= 40, 'name'= 'Task 40', 'period'= 900, 'execution_time'= 80, 'deadline'= 692, 'priority'= 39},
	{'id'= 41, 'name'= 'Task 41', 'period'= 100, 'execution_time'= 98, 'deadline'= 599, 'priority'= 4},
	{'id'= 42, 'name'= 'Task 42', 'period'= 400, 'execution_time'= 99, 'deadline'= 532, 'priority'= 66},
	{'id'= 43, 'name'= 'Task 43', 'period'= 600, 'execution_time'= 54, 'deadline'= 860, 'priority'= 85},
	{'id'= 44, 'name'= 'Task 44', 'period'= 700, 'execution_time'= 78, 'deadline'= 740, 'priority'= 94},
	{'id'= 45, 'name'= 'Task 45', 'period'= 1000, 'execution_time'= 57, 'deadline'= 183, 'priority'= 16},
	{'id'= 46, 'name'= 'Task 46', 'period'= 300, 'execution_time'= 86, 'deadline'= 143, 'priority'= 83},
	{'id'= 47, 'name'= 'Task 47', 'period'= 100, 'execution_time'= 57, 'deadline'= 272, 'priority'= 94},
	{'id'= 48, 'name'= 'Task 48', 'period'= 400, 'execution_time'= 31, 'deadline'= 211, 'priority'= 61},
	{'id'= 49, 'name'= 'Task 49', 'period'= 1000, 'execution_time'= 11, 'deadline'= 648, 'priority'= 21},
	{'id'= 50, 'name'= 'Task 50', 'period'= 700, 'execution_time'= 60, 'deadline'= 194, 'priority'= 38},
	{'id'= 51, 'name'= 'Task 51', 'period'= 100, 'execution_time'= 45, 'deadline'= 552, 'priority'= 10},
	{'id'= 52, 'name'= 'Task 52', 'period'= 600, 'execution_time'= 38, 'deadline'= 708, 'priority'= 10},
	{'id'= 53, 'name'= 'Task 53', 'period'= 400, 'execution_time'= 17, 'deadline'= 504, 'priority'= 81},
	{'id'= 54, 'name'= 'Task 54', 'period'= 200, 'execution_time'= 29, 'deadline'= 775, 'priority'= 53},
	{'id'= 55, 'name'= 'Task 55', 'period'= 400, 'execution_time'= 92, 'deadline'= 500, 'priority'= 9},
	{'id'= 56, 'name'= 'Task 56', 'period'= 900, 'execution_time'= 63, 'deadline'= 496, 'priority'= 93},
	{'id'= 57, 'name'= 'Task 57', 'period'= 800, 'execution_time'= 71, 'deadline'= 839, 'priority'= 46},
	{'id'= 58, 'name'= 'Task 58', 'period'= 300, 'execution_time'= 88, 'deadline'= 746, 'priority'= 20},
	{'id'= 59, 'name'= 'Task 59', 'period'= 900, 'execution_time'= 21, 'deadline'= 475, 'priority'= 3},
	{'id'= 60, 'name'= 'Task 60', 'period'= 800, 'execution_time'= 77, 'deadline'= 154, 'priority'= 53},
	{'id'= 61, 'name'= 'Task 61', 'period'= 800, 'execution_time'= 50, 'deadline'= 107, 'priority'= 58},
	{'id'= 62, 'name'= 'Task 62', 'period'= 400, 'execution_time'= 85, 'deadline'= 564, 'priority'= 74},
	{'id'= 63, 'name'= 'Task 63', 'period'= 1000, 'execution_time'= 12, 'deadline'= 181, 'priority'= 79},
	{'id'= 64, 'name'= 'Task 64', 'period'= 400, 'execution_time'= 16, 'deadline'= 648, 'priority'= 61},
	{'id'= 65, 'name'= 'Task 65', 'period'= 700, 'execution_time'= 75, 'deadline'= 309, 'priority'= 84},
	{'id'= 66, 'name'= 'Task 66', 'period'= 700, 'execution_time'= 45, 'deadline'= 511, 'priority'= 60},
	{'id'= 67, 'name'= 'Task 67', 'period'= 400, 'execution_time'= 71, 'deadline'= 77, 'priority'= 36},
	{'id'= 68, 'name'= 'Task 68', 'period'= 400, 'execution_time'= 15, 'deadline'= 798, 'priority'= 81},
	{'id'= 69, 'name'= 'Task 69', 'period'= 200, 'execution_time'= 93, 'deadline'= 993, 'priority'= 8},
	{'id'= 70, 'name'= 'Task 70', 'period'= 600, 'execution_time'= 86, 'deadline'= 177, 'priority'= 59},
	{'id'= 71, 'name'= 'Task 71', 'period'= 100, 'execution_time'= 42, 'deadline'= 170, 'priority'= 19},
	{'id'= 72, 'name'= 'Task 72', 'period'= 400, 'execution_time'= 69, 'deadline'= 846, 'priority'= 18},
	{'id'= 73, 'name'= 'Task 73', 'period'= 700, 'execution_time'= 44, 'deadline'= 857, 'priority'= 59},
	{'id'= 74, 'name'= 'Task 74', 'period'= 900, 'execution_time'= 35, 'deadline'= 891, 'priority'= 99},
	{'id'= 75, 'name'= 'Task 75', 'period'= 1000, 'execution_time'= 67, 'deadline'= 590, 'priority'= 48},
	{'id'= 76, 'name'= 'Task 76', 'period'= 600, 'execution_time'= 17, 'deadline'= 98, 'priority'= 9},
	{'id'= 77, 'name'= 'Task 77', 'period'= 600, 'execution_time'= 81, 'deadline'= 568, 'priority'= 84},
	{'id'= 78, 'name'= 'Task 78', 'period'= 900, 'execution_time'= 65, 'deadline'= 374, 'priority'= 46},
	{'id'= 79, 'name'= 'Task 79', 'period'= 200, 'execution_time'= 53, 'deadline'= 904, 'priority'= 41},
	{'id'= 80, 'name'= 'Task 80', 'period'= 600, 'execution_time'= 66, 'deadline'= 384, 'priority'= 38},
	{'id'= 81, 'name'= 'Task 81', 'period'= 800, 'execution_time'= 57, 'deadline'= 787, 'priority'= 30},
	{'id'= 82, 'name'= 'Task 82', 'period'= 300, 'execution_time'= 94, 'deadline'= 138, 'priority'= 22},
	{'id'= 83, 'name'= 'Task 83', 'period'= 1000, 'execution_time'= 90, 'deadline'= 748, 'priority'= 85},
	{'id'= 84, 'name'= 'Task 84', 'period'= 700, 'execution_time'= 66, 'deadline'= 773, 'priority'= 12},
	{'id'= 85, 'name'= 'Task 85', 'period'= 700, 'execution_time'= 97, 'deadline'= 953, 'priority'= 63},
	{'id'= 86, 'name'= 'Task 86', 'period'= 600, 'execution_time'= 36, 'deadline'= 984, 'priority'= 35},
	{'id'= 87, 'name'= 'Task 87', 'period'= 500, 'execution_time'= 90, 'deadline'= 965, 'priority'= 84},
	{'id'= 88, 'name'= 'Task 88', 'period'= 800, 'execution_time'= 10, 'deadline'= 465, 'priority'= 90},
	{'id'= 89, 'name'= 'Task 89', 'period'= 700, 'execution_time'= 26, 'deadline'= 821, 'priority'= 22},
	{'id'= 90, 'name'= 'Task 90', 'period'= 100, 'execution_time'= 75, 'deadline'= 280, 'priority'= 58},
	{'id'= 91, 'name'= 'Task 91', 'period'= 900, 'execution_time'= 91, 'deadline'= 996, 'priority'= 14},
	{'id'= 92, 'name'= 'Task 92', 'period'= 800, 'execution_time'= 44, 'deadline'= 386, 'priority'= 77},
	{'id'= 93, 'name'= 'Task 93', 'period'= 1000, 'execution_time'= 32, 'deadline'= 496, 'priority'= 83},
	{'id'= 94, 'name'= 'Task 94', 'period'= 1000, 'execution_time'= 12, 'deadline'= 238, 'priority'= 85},
	{'id'= 95, 'name'= 'Task 95', 'period'= 500, 'execution_time'= 95, 'deadline'= 372, 'priority'= 42},
	{'id'= 96, 'name'= 'Task 96', 'period'= 1000, 'execution_time'= 89, 'deadline'= 375, 'priority'= 66},
	{'id'= 97, 'name'= 'Task 97', 'period'= 400, 'execution_time'= 13, 'deadline'= 521, 'priority'= 64},
	{'id'= 98, 'name'= 'Task 98', 'period'= 600, 'execution_time'= 34, 'deadline'= 442, 'priority'= 18},
	{'id'= 99, 'name'= 'Task 99', 'period'= 200, 'execution_time'= 21, 'deadline'= 378, 'priority'= 93},
	{'id'= 100, 'name'= 'Task 100', 'period'= 700, 'execution_time'= 67, 'deadline'= 825, 'priority'= 95},
]
